"""Server route, stack, and lead-source inventory data."""

APPLICATION_ROUTES = [('codestra.co', 'site/codestra', 'frontend', 'production', 'active', True, None, None),
 ('www.codestra.co', 'site/codestra', 'redirect', 'production', 'active', False, 'https://codestra.co', None),
 ('auth.codestra.co',
  'site/codestra-auth',
  'identity',
  'production',
  'active',
  False,
  None,
  None),
 ('social.codestra.co', 'site/codestra-social', 'social_application', 'production', 'active', False, None, None),
 ('ai.codestra.co', 'site/codestra-ai', 'ai_console', 'production', 'active', False, None, None),
 ('beyvra.com', 'site/beyvra', 'frontend', 'production', 'active', True, None, None),
 ('www.beyvra.com', 'site/beyvra', 'frontend', 'production', 'active', True, None, None),
 ('platform.beyvra.com', 'site/beyvra', 'platform_frontend', 'production', 'active', True, None, None),
 ('api.beyvra.com', 'site/beyvra', 'api', 'production', 'active', False, None, None),
 ('admin.beyvra.com', 'site/beyvra', 'admin', 'production', 'active', False, None, None),
 ('staging.beyvra.com', 'site/beyvra', 'frontend', 'staging', 'active', True, None, None),
 ('booked4seasons.com', 'site/booked4seasons', 'frontend', 'production', 'active', True, None, None),
 ('www.booked4seasons.com',
  'site/booked4seasons',
  'redirect',
  'production',
  'degraded',
  False,
  'https://booked4seasons.com',
  'TLS handshake fails before the configured redirect can complete'),
 ('breero.com', 'site/breero', 'frontend', 'production', 'active', True, None, None),
 ('www.breero.com', 'site/breero', 'redirect', 'production', 'active', False, 'https://breero.com', None),
 ('api.breero.com', 'site/breero', 'api', 'production', 'active', False, None, None),
 ('staging.breero.com', 'site/breero', 'frontend', 'staging', 'active', True, None, None),
 ('api-staging.breero.com', 'site/breero', 'api', 'staging', 'active', False, None, None)]
PROVIDER_ROUTES = [('klyrow.com', 'site/klyrow', 'frontend', 'production', 'active', True, None, None),
 ('www.klyrow.com', 'site/klyrow', 'frontend_or_redirect', 'production', 'active', True, None, None),
 ('app.klyrow.com', 'site/klyrow', 'application', 'production', 'active', False, None, None),
 ('api.klyrow.com', 'site/klyrow', 'api', 'production', 'active', False, None, None),
 ('track.klyrow.com', 'site/klyrow', 'tracking', 'production', 'active', False, None, None),
 ('bounce.klyrow.com', 'site/klyrow', 'bounce_callback', 'production', 'active', False, None, None),
 ('sms.telnexa.co', 'site/telnexa', 'sms_gateway', 'production', 'active', False, None, None),
 ('api.telnexa.co', 'site/telnexa', 'api', 'production', 'active', True, None, None),
 ('status.telnexa.co', 'site/telnexa', 'status', 'production', 'active', False, None, None),
 ('crawler.kyqra.com', 'site/kyqra-crawler', 'crawler_api', 'production', 'active', False, None, None)]
PRIVATE_ROUTES = [('telnexa-internal-mtls', 'site/telnexa', 'private_only', 'internal_mtls'),
 ('private-app-integration-loopback', 'site/private-app-integration', 'private_only', 'loopback_and_internal_mtls')]
STACKS = [('application-server-a', 'codestra', 'site/codestra', 'active', (), {}),
 ('application-server-a', 'codestra-auth', 'site/codestra-auth', 'active', (), {}),
 ('application-server-a', 'codestra-social', 'site/codestra-social', 'active', (), {}),
 ('application-server-a', 'codestra-ai', 'site/codestra-ai', 'active', (), {}),
 ('application-server-a', 'beyvra', 'site/beyvra', 'active', (), {}),
 ('application-server-a', 'booked4seasons', 'site/booked4seasons', 'degraded', (), {}),
 ('application-server-a', 'breero', 'site/breero', 'active', (), {}),
 ('provider-host',
  'klyrow',
  'site/klyrow',
  'active',
  ('integration/klyrow-email',
   'core/workers-scheduler',
   'integration/provider-billing',
   'integration/klyrow-smtp-relay',
   'integration/mautic',
   'integration/postal-email',
   'observability/grafana',
   'observability/prometheus',
   'platform/rabbitmq',
   'platform/postgresql',
   'platform/mariadb'),
  {}),
 ('provider-host',
  'telnexa',
  'site/telnexa',
  'active',
  ('integration/telnexa-sms',
   'integration/jasmin-sms',
   'integration/provider-billing',
   'integration/keycloak',
   'observability/prometheus',
   'observability/node-exporter',
   'platform/rabbitmq',
   'platform/redis',
   'platform/postgresql'),
  {}),
 ('provider-host',
  'kyqra-crawler',
  'site/kyqra-crawler',
  'active',
  ('integration/kyqra', 'integration/crawlee', 'testing/playwright', 'platform/postgresql', 'platform/redis'),
  {'technology_evidence': {'crawlee': 'runtime package or image not yet confirmed',
                           'playwright': 'browser worker observed; Playwright package or image not yet confirmed'}}),
 ('provider-host',
  'private-app-integration',
  'site/private-app-integration',
  'private_only',
  ('integration/private-app-gateway', 'platform/nginx-provider'),
  {'exposure': 'loopback_and_internal_mtls_only'}),
 ('provider-host',
  'codestra-business-scrapper',
  'site/codestra-business-scrapper',
  'not_deployed',
  ('integration/codestra-business-scrapper',),
  {'disposable_validation_containers': ['PostgreSQL 17', 'Redis 7.4'], 'source_checkout': '/opt/codestra-business-scrapper'})]
LEAD_SOURCES = [('codestra-public-form',
  'public_form',
  'site/codestra',
  ('codestra.co',),
  'active',
  'platform/caddy',
  ('site/codestra',
   'platform/caddy',
   'platform/kong',
   'integration/web-form-intake',
   'integration/private-app-gateway',
   'core/webhook-inbox-replay',
   'core/lead-intake-normalization',
   'core/event-ledger-outbox',
   'integration/odoo-19'),
  'create_or_update',
  'new',
  False,
  'only_when_consent_and_suppression_policy_pass'),
 ('beyvra-public-form',
  'public_form',
  'site/beyvra',
  ('beyvra.com', 'www.beyvra.com', 'platform.beyvra.com', 'staging.beyvra.com'),
  'active',
  'platform/caddy',
  ('site/beyvra',
   'platform/caddy',
   'platform/kong',
   'integration/web-form-intake',
   'integration/private-app-gateway',
   'core/webhook-inbox-replay',
   'core/lead-intake-normalization',
   'core/event-ledger-outbox',
   'integration/odoo-19'),
  'create_or_update',
  'new',
  False,
  'only_when_consent_and_suppression_policy_pass'),
 ('booked4seasons-public-form',
  'public_form',
  'site/booked4seasons',
  ('booked4seasons.com',),
  'active_with_degraded_www_tls',
  'platform/caddy',
  ('site/booked4seasons',
   'platform/caddy',
   'integration/web-form-intake',
   'integration/private-app-gateway',
   'core/webhook-inbox-replay',
   'core/lead-intake-normalization',
   'core/event-ledger-outbox',
   'integration/odoo-19'),
  'create_or_update',
  'new',
  False,
  'only_when_consent_and_suppression_policy_pass'),
 ('breero-public-form',
  'public_form',
  'site/breero',
  ('breero.com', 'staging.breero.com'),
  'active',
  'platform/caddy',
  ('site/breero',
   'platform/caddy',
   'platform/kong',
   'integration/web-form-intake',
   'integration/private-app-gateway',
   'core/webhook-inbox-replay',
   'core/lead-intake-normalization',
   'core/event-ledger-outbox',
   'integration/odoo-19'),
  'create_or_update',
  'new',
  False,
  'only_when_consent_and_suppression_policy_pass'),
 ('klyrow-public-form',
  'public_form',
  'site/klyrow',
  ('klyrow.com', 'www.klyrow.com'),
  'active_remote_provider',
  'platform/nginx-provider',
  ('site/klyrow',
   'platform/nginx-provider',
   'integration/web-form-intake',
   'integration/private-app-gateway',
   'core/webhook-inbox-replay',
   'core/lead-intake-normalization',
   'core/event-ledger-outbox',
   'integration/odoo-19'),
  'create_or_update',
  'new',
  False,
  'only_when_consent_and_suppression_policy_pass'),
 ('telnexa-public-form',
  'public_form',
  'site/telnexa',
  ('api.telnexa.co',),
  'active_remote_provider',
  'platform/nginx-provider',
  ('site/telnexa',
   'platform/nginx-provider',
   'integration/web-form-intake',
   'integration/private-app-gateway',
   'core/webhook-inbox-replay',
   'core/lead-intake-normalization',
   'core/event-ledger-outbox',
   'integration/odoo-19'),
  'create_or_update',
  'new',
  False,
  'only_when_consent_and_suppression_policy_pass'),
 ('kyqra-crawler-results',
  'crawler_result',
  'site/kyqra-crawler',
  ('crawler.kyqra.com',),
  'active_remote_provider',
  'platform/nginx-provider',
  ('site/kyqra-crawler',
   'integration/kyqra',
   'integration/private-app-gateway',
   'core/webhook-inbox-replay',
   'core/lead-intake-normalization',
   'core/event-ledger-outbox',
   'integration/odoo-19'),
  'create_or_update',
  'review_pending',
  True,
  False),
 ('codestra-business-scrapper-results',
  'scraper_result',
  'site/codestra-business-scrapper',
  (),
  'not_deployed',
  'integration/private-app-gateway',
  ('site/codestra-business-scrapper',
   'integration/codestra-business-scrapper',
   'integration/private-app-gateway',
   'core/webhook-inbox-replay',
   'core/lead-intake-normalization',
   'core/event-ledger-outbox',
   'integration/odoo-19'),
  'create_or_update',
  'review_pending',
  True,
  False)]

LEAD_REQUIRED_METADATA = (
    "tenant_id", "source_system", "source_kind", "source_route", "submission_id",
    "correlation_id", "causation_id", "idempotency_key", "captured_at",
    "schema_version", "provenance", "consent",
)

LEAD_DEDUPLICATION_ORDER = (
    "tenant_id + normalized_email",
    "tenant_id + normalized_e164_phone",
    "tenant_id + normalized_company_domain + normalized_company_name",
    "tenant_id + source_system + source_record_id",
)
