"""Supplemental workstream and dependency data."""

CANONICAL_CONTRACT_BRANCH = "core/integration-contracts"

STATUS_OVERRIDES = {'integration/beyvra': 'declared_active_scope',
 'integration/jasmin-sms': 'declared_remote_provider_scope',
 'integration/kyqra': 'declared_remote_provider_scope',
 'integration/mautic': 'declared_remote_provider_scope',
 'integration/postal-email': 'declared_remote_provider_scope',
 'platform/rabbitmq': 'declared_remote_provider_scope'}

WORKSTREAMS = {'core/lead-intake-normalization': ('shared-core',
                                    'required_shared_primitive',
                                    'Form, crawler and scraper lead normalization, consent, suppression, provenance, '
                                    'deduplication, review state, Odoo command mapping, and audit'),
 'integration/codestra-ai-console': ('application',
                                     'declared_active_scope',
                                     'Codestra AI console authentication, API contracts, tenant isolation, prompt and '
                                     'job metadata, audit, health, and safe integration boundaries'),
 'integration/codestra-business-scrapper': ('scraper',
                                            'source_checkout_not_deployed',
                                            'Codestra Business Scrapper source and result contracts, provenance, job '
                                            'isolation, review-only lead delivery, validation, and deployment '
                                            'readiness'),
 'integration/klyrow-smtp-relay': ('messaging',
                                   'declared_remote_provider_scope',
                                   'Klyrow SMTP relay submission, authentication, tenant and domain routing, queue '
                                   'ownership, bounce paths, health, and Postal compatibility'),
 'integration/postiz-social': ('social',
                               'declared_active_scope',
                               'Postiz social application integration, account authorization, publishing workflows, '
                               'callbacks, synchronization, and runtime health contracts'),
 'integration/private-app-gateway': ('gateway',
                                     'declared_private_scope',
                                     'Loopback and internal mTLS integration gateway, request authentication, tenant '
                                     'isolation, signed intake forwarding, health, and private routing'),
 'integration/provider-billing': ('billing',
                                  'declared_remote_provider_scope',
                                  'Klyrow and Telnexa billing APIs, workers and schedulers, tenant charging, '
                                  'idempotency, ledger events, reconciliation, and failure handling'),
 'integration/web-form-intake': ('intake',
                                 'required_shared_primitive',
                                 'Public website form intake, anti-abuse controls, consent capture, schema validation, '
                                 'idempotency, durable acceptance, and normalized lead forwarding'),
 'operations/application-host': ('operations',
                                 'declared_active_scope',
                                 'Application-host route inventory, Caddy coordination, Docker service ownership, safe '
                                 'restarts, host health, backups, and change records'),
 'operations/provider-host': ('operations',
                              'declared_remote_provider_scope',
                              'Provider-host Docker and containerd inventory, Nginx coordination, Fail2ban, SSH, cron, '
                              'logging, automatic updates, backups, and node health'),
 'platform/mariadb': ('platform',
                      'declared_remote_provider_scope',
                      'MariaDB schemas used by provider-host applications, least-privilege accounts, migrations, '
                      'backup, restore, health, and operational ownership'),
 'platform/nginx-provider': ('platform',
                             'declared_remote_provider_scope',
                             'Provider-host Nginx public and private mTLS routes, upstream health, TLS, route '
                             'ownership, access controls, and rollback-safe validation'),
 'site/beyvra': ('site',
                 'declared_active_scope',
                 'Beyvra public, www, platform, API, admin and staging routes, authentication, forms, releases, and '
                 'route health'),
 'site/booked4seasons': ('site',
                         'declared_degraded_scope',
                         'Booked4Seasons production site and www redirect, form intake, certificate and TLS '
                         'remediation, release identity, and route health'),
 'site/breero': ('site',
                 'declared_active_scope',
                 'Breero production and staging frontends and APIs, authentication, forms, release separation, route '
                 'health, and middleware intake'),
 'site/codestra': ('site',
                   'declared_active_scope',
                   'codestra.co production site and www redirect, public forms, route health, release identity, and '
                   'middleware intake contract'),
 'site/codestra-ai': ('site',
                      'declared_active_scope',
                      'ai.codestra.co AI console route, authentication, tenant isolation, API boundary, audit, and '
                      'route health'),
 'site/codestra-auth': ('site',
                        'declared_degraded_scope',
                        'auth.codestra.co authentication route, Keycloak upstream health, issuer continuity, 502 '
                        'remediation, and edge validation'),
 'site/codestra-business-scrapper': ('site',
                                     'source_checkout_not_deployed',
                                     'Codestra Business Scrapper source checkout and disposable validation '
                                     'dependencies, explicitly not deployed as an application'),
 'site/codestra-social': ('site',
                          'declared_active_scope',
                          'social.codestra.co Postiz social application route, authentication, social integration '
                          'contracts, callbacks, and route health'),
 'site/klyrow': ('site',
                 'declared_remote_provider_scope',
                 'Klyrow public sites, gateway, workers, billing, SMTP relay, Mautic, Postal, RabbitMQ, PostgreSQL, '
                 'MariaDB, Prometheus, Grafana, and route health'),
 'site/kyqra-crawler': ('site',
                        'declared_remote_provider_scope',
                        'Kyqra crawler API, HTTP worker, browser worker, callback worker, PostgreSQL, Redis, public '
                        'crawler route, and result delivery'),
 'site/private-app-integration': ('site',
                                  'declared_private_scope',
                                  'Private App Integration stack exposed only on loopback and the internal mTLS Nginx '
                                  'route, with no public route'),
 'site/telnexa': ('site',
                  'declared_remote_provider_scope',
                  'Telnexa SMS, billing, Keycloak, RabbitMQ, Redis, PostgreSQL, Prometheus, Node Exporter, public '
                  'routes, internal mTLS, and route health')}

DEPENDENCY_EXTRAS = {'core/lead-intake-normalization': ('core/event-ledger-outbox',
                                    'core/webhook-inbox-replay',
                                    'core/workers-scheduler',
                                    'integration/keycloak'),
 'integration/codestra-ai-console': ('core/event-ledger-outbox',
                                     'core/webhook-inbox-replay',
                                     'core/workers-scheduler',
                                     'integration/keycloak'),
 'integration/codestra-business-scrapper': ('core/workers-scheduler',
                                            'core/lead-intake-normalization',
                                            'integration/keycloak'),
 'integration/klyrow-smtp-relay': ('integration/postal-email', 'integration/keycloak'),
 'integration/postiz-social': ('core/event-ledger-outbox',
                               'core/webhook-inbox-replay',
                               'core/workers-scheduler',
                               'integration/keycloak'),
 'integration/private-app-gateway': ('core/webhook-inbox-replay', 'integration/keycloak'),
 'integration/provider-billing': ('core/event-ledger-outbox',
                                  'core/workers-scheduler',
                                  'integration/keycloak',
                                  'platform/postgresql',
                                  'platform/rabbitmq'),
 'integration/web-form-intake': ('integration/private-app-gateway',
                                 'core/webhook-inbox-replay',
                                 'core/lead-intake-normalization',
                                 'integration/keycloak'),
 'operations/application-host': ('platform/caddy',
                                 'platform/kong',
                                 'integration/keycloak',
                                 'observability/node-exporter',
                                 'observability/blackbox-exporter'),
 'operations/provider-host': ('platform/nginx-provider',
                              'platform/rabbitmq',
                              'platform/postgresql',
                              'platform/redis',
                              'platform/mariadb',
                              'observability/node-exporter',
                              'observability/prometheus'),
 'platform/mariadb': (),
 'platform/nginx-provider': ('integration/keycloak',),
 'site/beyvra': ('platform/caddy',
                 'platform/kong',
                 'integration/beyvra',
                 'integration/web-form-intake',
                 'integration/keycloak',
                 'operations/application-host'),
 'site/booked4seasons': ('platform/caddy',
                         'integration/web-form-intake',
                         'operations/application-host',
                         'observability/blackbox-exporter'),
 'site/breero': ('platform/caddy',
                 'platform/kong',
                 'integration/web-form-intake',
                 'integration/keycloak',
                 'operations/application-host'),
 'site/codestra': ('platform/caddy',
                   'platform/kong',
                   'integration/web-form-intake',
                   'integration/keycloak',
                   'operations/application-host'),
 'site/codestra-ai': ('platform/caddy',
                      'platform/kong',
                      'integration/codestra-ai-console',
                      'integration/keycloak',
                      'operations/application-host'),
 'site/codestra-auth': ('platform/caddy',
                        'integration/keycloak',
                        'operations/application-host',
                        'observability/blackbox-exporter'),
 'site/codestra-business-scrapper': ('integration/codestra-business-scrapper', 'operations/provider-host'),
 'site/codestra-social': ('platform/caddy',
                          'integration/postiz-social',
                          'integration/postly-social',
                          'integration/keycloak',
                          'operations/application-host'),
 'site/klyrow': ('platform/nginx-provider',
                 'integration/klyrow-email',
                 'integration/klyrow-smtp-relay',
                 'integration/mautic',
                 'integration/postal-email',
                 'integration/provider-billing',
                 'platform/rabbitmq',
                 'platform/postgresql',
                 'platform/mariadb',
                 'observability/prometheus',
                 'observability/grafana',
                 'operations/provider-host'),
 'site/kyqra-crawler': ('platform/nginx-provider',
                        'integration/kyqra',
                        'platform/postgresql',
                        'platform/redis',
                        'operations/provider-host'),
 'site/private-app-integration': ('platform/nginx-provider',
                                  'integration/private-app-gateway',
                                  'operations/provider-host'),
 'site/telnexa': ('platform/nginx-provider',
                  'integration/telnexa-sms',
                  'integration/jasmin-sms',
                  'integration/provider-billing',
                  'integration/keycloak',
                  'platform/rabbitmq',
                  'platform/redis',
                  'platform/postgresql',
                  'observability/prometheus',
                  'observability/node-exporter',
                  'operations/provider-host')}

PROVIDER_COMPONENTS = {'site/klyrow': ['integration/klyrow-smtp-relay',
                 'integration/provider-billing',
                 'integration/mautic',
                 'integration/postal-email',
                 'platform/rabbitmq',
                 'platform/mariadb'],
 'site/telnexa': ['integration/jasmin-sms',
                  'integration/provider-billing',
                  'platform/rabbitmq',
                  'platform/redis',
                  'platform/postgresql']}

POLICIES = {
    "branches_start_from_reviewed_main": True,
    "all_new_branches_depend_on_canonical_contracts": True,
    "site_branches_are_not_deployment_branches": True,
    "all_links_require_authentication": True,
    "external_effects_disabled_by_default": True,
    "all_public_forms_use_middleware_intake": True,
    "direct_site_crawler_or_scraper_write_to_odoo": False,
    "crawler_and_scraper_odoo_records_start_review_pending": True,
    "external_contact_disabled_for_discovered_records": True,
}
