import {useEffect,useState} from "react";
import {supervisorService,type CallDetail,type CallSearchItem,type SupervisorDashboard,type CallbackSupervisorDashboard,type CallbackCampaignMetric} from "../../supervisor";

const categories=["greeting","verification","product_knowledge","compliance","call_control","empathy","closing"] as const;
export function SupervisorModule(){
  const [dashboard,setDashboard]=useState<SupervisorDashboard>(),[calls,setCalls]=useState<CallSearchItem[]>([]),[detail,setDetail]=useState<CallDetail>();
  const [callbackDashboard,setCallbackDashboard]=useState<CallbackSupervisorDashboard>(),[campaignCallbacks,setCampaignCallbacks]=useState<CallbackCampaignMetric[]>([]);
  const [query,setQuery]=useState(""),[error,setError]=useState(""),[scores,setScores]=useState<Record<string,number>>(Object.fromEntries(categories.map(item=>[item,5]))),[comment,setComment]=useState(""),[coaching,setCoaching]=useState(false),[message,setMessage]=useState("");
  const search=async()=>{try{const result=await supervisorService.search(query?{phone:query}:{limit:50});setCalls(result.items);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Call search unavailable");}};
  useEffect(()=>{const controller=new AbortController();void Promise.all([supervisorService.dashboard(controller.signal).then(setDashboard),supervisorService.search({limit:50},controller.signal).then(result=>setCalls(result.items)),supervisorService.callbackDashboard(controller.signal).then(setCallbackDashboard),supervisorService.campaignCallbackDashboard(controller.signal).then(result=>setCampaignCallbacks(result.campaigns))]).catch(reason=>setError(reason instanceof Error?reason.message:"Supervisor data unavailable"));return()=>controller.abort();},[]);
  const open=async(callId:string)=>{try{setDetail(await supervisorService.detail(callId));setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Call detail unavailable");}};
  const submitQa=async()=>{if(!detail)return;try{const result=await supervisorService.score(detail.call.call_id,scores,comment,coaching);setMessage(`QA submitted: ${result.score.toFixed(1)}%`);if(coaching){const due=new Date(Date.now()+7*86400000).toISOString().slice(0,10);await supervisorService.coaching(result.review_id,due,comment);setMessage(`QA ${result.score.toFixed(1)}% submitted and coaching assigned`);}await open(detail.call.call_id);}catch(reason){setMessage(reason instanceof Error?reason.message:"QA submission denied");}};
  return <div className="supervisor-workspace">
    <section className="module" aria-labelledby="callback-supervisor-heading"><div className="module-title"><h2 id="callback-supervisor-heading">Callback operations</h2><span className="badge info">Tenant and campaign scoped</span></div><div className="supervisor-counts">{Object.entries(callbackDashboard?.counts??{}).map(([state,count])=><div key={state}><strong>{count}</strong><span>{state}</span></div>)}</div><div className="call-results">{callbackDashboard?.agents.map(agent=><div className="agent-row" key={agent.agent_id}><span><strong>{agent.agent_id}</strong><small>{agent.scheduled} scheduled · {agent.completed} completed · {agent.missed} missed · {agent.overdue} overdue</small></span><span>{Math.round(agent.completion_rate*100)}% · {Math.round(agent.average_lateness_seconds)}s late</span></div>)}</div></section>
    <section className="module" aria-labelledby="callback-campaign-heading"><div className="module-title"><h2 id="callback-campaign-heading">Campaign callbacks</h2></div><div className="call-results">{campaignCallbacks.map(campaign=><div className="agent-row" key={campaign.campaign_id}><span><strong>{campaign.campaign_id}</strong><small>{campaign.scheduled} scheduled · {campaign.due} due · {campaign.completed} completed · {campaign.missed} missed</small></span><span>{campaign.overdue} overdue · {campaign.escalated} escalated</span></div>)}</div></section>
    <section className="module"><div className="module-title"><h2>Supervisor visibility</h2><span className="badge info">Server-scoped</span></div>{error&&<p role="alert" className="inline-alert">{error}</p>}<div className="supervisor-counts">{Object.entries(dashboard?.counts??{}).map(([state,count])=><div key={state}><strong>{count}</strong><span>{state}</span></div>)}</div>{dashboard&&!dashboard.queue_metrics.available&&<p className="message">Queue metrics unavailable: {dashboard.queue_metrics.reason}</p>}<div className="team">{dashboard?.agents.map(agent=><button className="agent-row" key={agent.agent_id} onClick={()=>agent.call_id&&void open(agent.call_id)} disabled={!agent.call_id}><span className={`presence ${agent.status}`}/><span><strong>{agent.name}</strong><small>Ext {agent.extension} · {agent.campaigns.join(", ")}{agent.customer?` · ${agent.customer}`:""}</small></span><span className="badge">{agent.status}</span></button>)}</div></section>
    <section className="module"><div className="module-title"><h2>Call search</h2></div><div className="search-row"><label className="field"><span>Normalized phone</span><input value={query} onChange={event=>setQuery(event.target.value)}/></label><button onClick={()=>void search()}>Search</button></div><div className="call-results">{calls.map(call=><button key={call.call_id} onClick={()=>void open(call.call_id)}><span><strong>{call.customer??call.phone}</strong><small>{call.campaign} · {call.agent} · {call.direction}</small></span><span>{call.disposition??call.call_id}</span></button>)}</div></section>
    {detail&&<section className="module supervisor-detail"><div className="module-title"><h2>{detail.call.customer??detail.call.phone}</h2><span className="badge good">{detail.call.state}</span></div><dl className="facts"><div><dt>Call ID</dt><dd>{detail.call.call_id}</dd></div><div><dt>Campaign / agent</dt><dd>{detail.call.campaign} · {detail.call.agent}</dd></div><div><dt>Disposition</dt><dd>{detail.call.disposition??"—"}</dd></div><div><dt>Recording</dt><dd>{detail.recording.status} · public URL: none</dd></div></dl><h3>Timeline</h3><ol className="timeline">{detail.timeline.map(item=><li key={`${item.sequence}-${item.event}`}><time>{new Date(item.time).toLocaleTimeString()}</time><strong>{item.event}</strong><small>{item.source} · #{item.sequence}</small></li>)}</ol><h3>QA score</h3><div className="qa-grid">{categories.map(category=><label className="field" key={category}><span>{category.replaceAll("_"," ")}</span><input type="number" min="0" max="5" value={scores[category]} onChange={event=>setScores(current=>({...current,[category]:Number(event.target.value)}))}/></label>)}</div><label className="field"><span>QA comments</span><textarea value={comment} onChange={event=>setComment(event.target.value)}/></label><label className="toggle"><input type="checkbox" checked={coaching} onChange={event=>setCoaching(event.target.checked)}/> Coaching required</label><button onClick={()=>void submitQa()}>Submit QA review</button>{message&&<p role="status">{message}</p>}</section>}
  </div>;
}
